---
board: ["nice_nano_v2"]
shield: ["unicorne_left", "unicorne_right"]
include:
  - board: nice_nano_v2
    shield: unicorne_left
  - board: nice_nano_v2
    shield: unicorne_right
  - board: nice_nano_v2
    shield: settings_reset
